; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericAT32F425K8U7-4]
platform = arterytekat32
board = genericAT32F425K8U7-4
framework = at32firmlib
board_build.ldscript = ld/AT32F425x8_FLASH.ld
; BOARD_DEBUG=0 compiles the USART1 log out of the image. Set 1 to print.
build_flags = -Iinclude -DBOARD_DEBUG=0
